schema_version = "1.0.0"
id = "node_mini_map"
version = "1.0.0"
name = "Node Mini Map"
tagline = "Mini Map overlay for the Node Editor"
maintainer = "Nadir Perazzo"
type = "add-on"
tags = ["Node Editor", "User Interface"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
