schema_version = "1.0.0"
id = "nodemap"
version = "1.2.2"
name = "Nodemap"
tagline = "Minimap overlay for the Node Editor"
maintainer = "Nadir Perazzo"
website = "https://github.com/n4dirp/Nodemap"
type = "add-on"
tags = ["Node", "User Interface"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
