"""Provide the default preset for the minimap."""

import bpy

addon_id = next((ext.module for ext in bpy.context.preferences.addons if ext.module.endswith("nodemap")), "nodemap")
settings = bpy.context.preferences.addons[addon_id].preferences.settings

settings.dock_mode = 'CORNER'
settings.corner_position = 'TOP_LEFT'
settings.edge_position = 'TOP_BORDER'
settings.offset_x = 0
settings.offset_y = 0
settings.use_snap_to_borders = True
settings.show_node_count = True
settings.show_frames = True
settings.show_node_outline = True
settings.show_socket_indicators = True
settings.show_reroutes = True
settings.show_wires = True
settings.show_type_list = False
settings.show_type_colors = True
settings.type_list_sort = 'NAME'
settings.type_list_font_size = 10
settings.type_list_width_percent = 40
settings.show_search_bar = True
settings.show_frame_all_button = True
settings.show_frame_view_button = True
settings.show_frame_selected_button = False
settings.show_list_toggle_button = True
settings.show_move_button = True
settings.show_node_labels = True
settings.compact_node_labels = True
settings.show_frame_labels = True
settings.minimap_width = 400
settings.minimap_height = 100
settings.max_width_percent = 100
settings.max_height_percent = 100
settings.opacity = 1.0
settings.use_custom_viewport_fill = True
settings.viewport_fill_color = (0.278, 0.447, 0.702, 1.0)
settings.show_viewport_overlay = True
settings.viewport_overlay_color = (0.1, 0.1, 0.1, 0.5)
settings.use_custom_background = False
settings.background_color = (0.2, 0.2, 0.2, 1.0)
settings.use_custom_text = False
settings.text_color = (1.0, 1.0, 1.0, 1.0)
settings.show_text_shadow = True
settings.show_node_colors = True
settings.show_wire_color = True
settings.use_custom_noodle_curving = False
settings.noodle_curving = 5
settings.wire_thickness = 0.5
settings.wire_opacity = 0.5
settings.scroll_wheel_mode = 'NODE_EDITOR'
settings.left_click_action = 'PAN'
settings.right_click_action = 'SELECT_FRAME'
settings.pan_speed = 'FAST'
settings.frame_view_fill = True
settings.interactive = True
settings.follow_view = False
settings.highlight_selected_wires = True
settings.use_animations = True
settings.show_by_default = False
settings.debounce_delay = 0.1
